- name: This is my first yaml playbook
  become: true
  hosts: localhost
  tasks:
  - name: this is fist task
    ansible.builtin.dnf:
      nginx: installed
      state: present
      service: started
