- name: This is my first yaml playbook
  become: true
  hosts: web
  tasks:
  - name: this is fist task
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      


#can't we put 2 buit in commands under same name ?
#should we need separate everytime ?
