- name: This is the example playbook for defining variable inside the playbook
  hosts: localhost
  vars:
    name: Mahendhar
    age: 32
    country: India
  tasks:
  - name: To display variables information
    ansible.builtin.debug:
      msg: Hi This is {{name}} and may age is {{age}} , am from {{country}}