- name: playbook to check which variable is prioritised? vars in play or vars in tasks.
  hosts: localhost
  vars:     # --> These are variables under play
    course: daws
    location: hyd
    duration: "3 months"
  tasks:
    - name: defining variables under tasks   # --> These are variables tasks
      vars:
        course: devops-aws
        age: 32
        location: hyd
      ansible.builtin.debug:
        msg: Hi am doing {{course}}
    
    - name: Not defining variable here under tasks
      ansible.builtin.debug:
        msg: Hi am doing {{course}}



# Below is the output:

# Here, Variables mentioned in tasks will be prioritised first then next, variables in play will be considered.

# TASK [defining variables under tasks] *****************************************************************************************************************
# ok: [localhost] => {
#     "msg": "Hi am doing devops-aws"
# }

# TASK [Not defining variable here under tasks] *********************************************************************************************************
# ok: [localhost] => {
#     "msg": "Hi am doing daws"
