- name: data types
  hosts: localhost
  vars:
    course: DevOps with AWS   # this is string
    tools:     #this is list 
      - shell
      - Linux
      - AWS
    experience:  #this is map/dictonary
      AWS: 2
      devops: 3   #number
      shell: 2
      k8s: 2
    realproject: true  #boolean
  tasks:
  - name: print the defined variables
    ansible.builtin.debug:
      msg: "course: {{course}}, tool covered: {{tools}}, experience is: {{experience}}, is project real: {{realproject}}"
