- name: data types
  hosts: localhost
  vars:
    course: DevOps with AWS
    tools:
      - shell
      - Linux
      - AWS
    experience:
      AWS: 2
      devops: 3
      shell: 2
      k8s: 2
    realproject: true
  tasks:
  - name: print the defined variables
    ansible.builtin.debug:
      msg: "course: {{course}}, tool covered: {{tools}}, experience is: {{experience}}, is project real: {{realproject}}"