- name: ansible conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id test
    register: USER
    ignore_errors: true
  
  - name: print user information
    ansible.builtin.debug:
      msg: "user info: {{USER}}"