- name: ansible conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id user
    register: USER
    ignore_errors: true
  
  - name: print user information
    ansible.builtin.debug:
      msg: "user is: {{USER}}"
  
  - name: Add user if not exist
    ansible.builtin.command: useradd test
  