- name: Check Number and convert text into number(integer)
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: Please enter the number
    private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: " Given number {{ number }} is less than 10"
    when: number < 10