- name: Executing loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - mahi
    - mani
    - hero


# > The value for the item parameter is called from the loop (mahi mani here).

- name: Install packages from loops
  hosts: localhost
  tasks:
  - name: install rpms
    ansible.builtin.debug:
      msg:
        name: "{{ item }}"
        state: present
      loop:
      - ansible
      - mysql
      - nginx