- name: backend server installation and configuration
  hosts: backend
  become: yes
  vars:
    login_password: ExpenseApp@1
    login_host: db.mahidevops.cloud
  tasks:
  - name: disable nodejs
    command: dnf module disable nodejs -y

  - name: enable nodejs
    command: dnf module enable nodejs:20 -y

  - name: install nodejs
    dnf:
      name: nodejs
      state: installed
  
  - name: add expense user
    user:
      name: expense
  
  - name: create /app directory
    file:
      path: /app
      state: directory
  
  - name: download the application code
    get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: extract the code
    unarchive:
       src: /tmp/backend.zip
       dest: /app
       remote_src: yes

  - name: Install nodejs dependencies
    command: npm install
    args:
      chdir: /app
  
  - name: copy backend service to the systemd location
    copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: install mysql cliet on backend server
    dnf:
      name: mysql
      state: installed

  - name: install python and mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: import data/schema into mysql
    community.mysql.mysql_db:
      name: all
      state: import
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      target: /app/schema/backend.sql

  - name: reload service daemon
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: start and enable backend service
    service:
      name: backend
      state: started
      enabled: yes
