- name: configure DB server
  hosts: db
  vars:
    login_host: db.mahidevops.cloud
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter mysql root password
    private: no
  tasks:
  - name: install mysql-server 
    dnf:
      name: mysql-server
      state: installed
  
  - name: start and enable mysql service
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11

  # check if DB password is already set or not

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_host: "{{ login_host }}"
      login_password: "{{ mysql_root_password }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print above DB connection output
    debug:
      msg: "output is: {{ mysql_connection_output }}"

  - name: setup mysql root password
    command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
