- name: install packages from loops
  hosts: localhost
  become: yes
  tasks:
  - name: install rpms
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - ansible
    - mysql


- name: install and absent rpms
  hosts: localhost
  become: yes
  tasks:
  - name: install rpms
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'absent'}
    - { name: 'nginx', state: 'absent'}
    - { name: 'mysql', state: 'latest'}